### ISSUE TITLE
📚 Evitar llamadas estáticas en Métodos No Estáticos

### ISSUE THREAD

**Issue by gogl92** [phpcfdi/rfc#1]
En la documentación se menciona:

```
RfcFaker::mexicanRfcFisica() para persona física (13 posiciones).
RfcFaker::mexicanRfcMoral() para persona moral (12 posiciones).
RfcFaker::mexicanRfc() indistintamente una persona moral o física.
```

Pero estos métodos son estáticos, las llamadas deben de ser dinámicas o volver los métodos estáticos.

**Comment by eclipxe13** [comment]
Gracias, por favor, revisa la documentación del archivo https://github.com/phpcfdi/rfc/blob/master/develop/RfcFaker.md en donde se muestra cómo usar la librería en conjunto con `fzaninotto/Faker`. La liga está desde el README como "Generador de RFC ficticios".

Los métodos no son estáticos, es la forma de "documentarlos", no de usarlos.

Si crees que la documentación podría ser más entendible (por ejemplo, moviendo la liga de la documentación del generador a la sección de "Generador de RFC", puedes enviar un PR con la mejora.

También es probable que cambie la librería porque el proyecto `fzaninotto/Faker` ha sido deprecado (archivado por el autor) y me parece que fue readoptado por la comunidad en `fakerphp/faker`. Es probable que con este cambio hagan algunas correcciones de cómo funciona y cómo se implementan nuevos generadores, así que eso implicaría cambios importantes al generador que ofrece este proyecto. También estamos abiertos a contribuciones en este tema.
